name: kaggle_web_traffic_forecasting

channels:
  - conda-forge

dependencies:
  - python=3.8.1
  - pip=20.0.2

  - pip:
    - markdown>=3.1.1
    - pylint>=2.4.4
    - pep8>=1.7.1
    - autopep8>=1.5
    - pycodestyle>=2.5.0
