name: kaggle_web_traffic_forecasting

channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - pip=19.0.3
  - pyspark=2.4.4
  - six=1.14.0
  - pandas=0.24.2
  - numpy=1.16.2
  - scipy=1.2.1
  - jupyter=1.0*
  - ipykernel=5.1*

  - pip:
    - markdown>=3.1.1
    - pylint>=2.4.4
    - pep8>=1.7.1
    - autopep8>=1.5
    - pycodestyle>=2.5.0
