# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - master

jobs:
- job: 'Continous_integration_package'
  pool:
    name: Hosted Ubuntu 1604
  steps:

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - task: Bash@3
    displayName: Create Anaconda environment
    inputs:
      filePath: './src/CreateCondaEnvironment.sh'

  - task: Bash@3
    displayName: Run pylint
    inputs:
      targetType: 'inline'
      script: 'source activate kaggle_web_traffic_forecasting && pylint --rcfile=src/.pylintrc src/kaggle_web_traffic_forecasting || true'
      failOnStderr: false

  - task: PublishPipelineArtifact@0
    displayName: 'Publish code package'
    inputs:
      artifactName: 'kaggle_web_traffic_forecasting'
      targetPath: '$(Build.Repository.LocalPath)'
